import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/lib/reactQuery/queryClient";
import { ToastContainer } from 'react-toastify'
import { UserContextProvider } from "@/contexts/userContext";
import { StudentsContextProvider } from "@/contexts/studentsContext";
import { StaffContextProvider } from "@/contexts/staffContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <UserContextProvider>
            <StudentsContextProvider>
              <StaffContextProvider>
                {children}
              </StaffContextProvider>
            </StudentsContextProvider>
          </UserContextProvider>
        </QueryProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
